# cargo-features = ["codegen-backend"]
[workspace]

resolver = "2"

members = ["console", "lang"]

[workspace.package]
name = "orcvs"
default-run = "orcvs"

[profile.dev]
opt-level = 1
split-debuginfo = "unpacked"
# codegen-backend = "cranelift"

# [profile.dev.package."*"]
# opt-level = 3
[profile.dev.package]
serde_derive.opt-level = 3
syn.opt-level = 3
quote.opt-level = 3
proc-macro2.opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
codegen-units = 1
strip = "symbols"
lto = true

[profile.ci]
inherits = "dev"
debug = false
incremental = false

[profile.profiling]
inherits = "release"
debug = true
