# cargo-features = ["codegen-backend"]
[workspace]

resolver = "2"

members = ["console", "lang"]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
# codegen-backend = "cranelift"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
strip = "symbols"
lto = true

[profile.ci]
inherits = "dev"
debug = false
incremental = false

[profile.profiling]
inherits = "release"
debug = true
