[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.4", default-features = false }
serde = { version = "1.0.203", default-features = false }
# miette = { version = "7.2.0", features = ["fancy"] }
# miette = { version = "7.2.0" }
thiserror = "1.0.58"
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", features = [
    "fmt",
], default-features = false }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "parser_benchmark"
harness = false

# [[bin]]
# name = "lang"
# src = "src/main.rs"
