[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
# enum_dispatch = "0.3.13"
lazy_static = "1.4.0"
smallvec = "1.13.2"
# nohash-hasher = "0.2.0"
# miette = { version = "7.2.0", features = ["fancy"] }
# miette = { version = "7.2.0" }
thiserror = "1.0.58"
# tinyvec = "1.6.0"
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = "0.3.18"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "parser_benchmark"
harness = false

[[bin]]
name = "lang"
src = "src/main.rs"
