[package]
name = "console"
version = "0.1.0"
authors = []
edition = "2021"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]
rust-version = "1.76"

[lib]
name = "console"
path = "src/lib.rs"

[[bin]]
name = "console"
path = "src/main.rs"

[[bench]]
name = "source_benchmark"
harness = false

[features]
default = []
persistence = ["dep:serde", "eframe/persistence"]

[dependencies]
lang = { path = "../lang" }
arrayvec = { version = "0.7.4", default-features = false }
eframe = { version = "0.28.0", default-features = false, features = [
    "glow",
    "default_fonts",
] }
egui = { version = "0.28.0", default-features = false }
nohash-hasher = "0.2.0"
rand = "0.8.5"
serde = { version = "1", features = ["derive"], optional = true }
tokio = { version = "1.39.2", features = ["full"] }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "ansi",
    "env-filter",
    "std",
] }
tokio-util = "0.7.11"

[dev-dependencies]
criterion = { version = "0.5.1" }
tokio = { version = "1.39.2", features = ["full", "test-util"] }


[package.metadata.docs.rs]
all-features = true
targets = [
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "wasm32-unknown-unknown",
]

# native:
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# env_logger = "0.10"


# web:
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen-futures = "0.4"
