// Generated by egui-themer (https://github.com/grantshandy/egui-themer).

use eframe::egui;

use egui::{
    epaint::Shadow,
    style::{
        HandleShape, Interaction, NumericColorSpace, Selection, Spacing, WidgetVisuals, Widgets,
    },
    vec2, Color32, CornerRadius, Margin, Stroke, Style, Vec2, Visuals,
};

use crate::Color;

pub fn style() -> Style {
    Style {
        // override the text styles here:
        // override_text_style: Option<TextStyle>

        // override the font id here:
        // override_font_id: Option<FontId>

        // set your text styles here:
        // text_styles: BTreeMap<TextStyle, FontId>,

        // set your drag value text style:
        // drag_value_text_style: TextStyle,
        spacing: Spacing {
            item_spacing: Vec2 { x: 8.0, y: 3.0 },
            window_margin: Margin {
                left: 6,
                right: 6,
                top: 6,
                bottom: 6,
            },
            button_padding: Vec2 { x: 4.0, y: 1.0 },
            menu_margin: Margin {
                left: 6,
                right: 6,
                top: 6,
                bottom: 6,
            },
            indent: 18.0,
            interact_size: Vec2 { x: 40.0, y: 18.0 },
            slider_width: 100.0,
            combo_width: 100.0,
            text_edit_width: 280.0,
            extra_text_line_spacing: 0.0,
            icon_width: 14.0,
            icon_width_inner: 8.0,
            icon_spacing: 4.0,
            tooltip_width: 600.0,
            indent_ends_with_horizontal_line: false,
            combo_height: 200.0,
            slider_rail_height: 8.0,
            default_area_size: vec2(600.0, 400.0),
            menu_width: 400.0,
            menu_spacing: 2.0,
            scroll: Default::default(),
        },
        interaction: Interaction {
            resize_grab_radius_side: 5.0,
            resize_grab_radius_corner: 10.0,
            show_tooltips_only_when_still: true,
            interact_radius: 5.0,
            tooltip_delay: 0.5,
            tooltip_grace_time: 0.2,
            selectable_labels: true,
            multi_widget_text_select: true,
        },
        visuals: Visuals {
            dark_mode: true,
            override_text_color: None,
            widgets: Widgets {
                noninteractive: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(27, 27, 27, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(27, 27, 27, 255),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(60, 60, 60, 255),
                    },
                    corner_radius: CornerRadius {
                        nw: 2,
                        ne: 2,
                        sw: 2,
                        se: 2,
                    },
                    fg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(140, 140, 140, 255),
                    },
                    expansion: 0.0,
                },
                inactive: WidgetVisuals {
                    bg_fill: Color::rgb(60, 60, 60).build(),
                    weak_bg_fill: Color::rgb(60, 60, 60).build(),

                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::TRANSPARENT,
                    },
                    corner_radius: CornerRadius {
                        nw: 1,
                        ne: 1,
                        sw: 1,
                        se: 1,
                    },
                    fg_stroke: Stroke {
                        width: 1.0,
                        color: Color::rgb(180, 180, 180).build(),
                    },
                    expansion: 0.0,
                },
                hovered: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(70, 70, 70, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(70, 70, 70, 255),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(150, 150, 150, 255),
                    },
                    corner_radius: CornerRadius {
                        nw: 3,
                        ne: 3,
                        sw: 3,
                        se: 3,
                    },
                    fg_stroke: Stroke {
                        width: 1.5,
                        color: Color32::from_rgba_premultiplied(240, 240, 240, 255),
                    },
                    expansion: 1.0,
                },
                active: WidgetVisuals {
                    bg_fill: Color::rgb(55, 55, 55).build(),
                    weak_bg_fill: Color::rgb(55, 55, 55).build(),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color::rgb(255, 255, 255).build(),
                    },
                    corner_radius: CornerRadius {
                        nw: 2,
                        ne: 2,
                        sw: 2,
                        se: 2,
                    },
                    fg_stroke: Stroke {
                        width: 2.0,
                        color: Color32::from_rgba_premultiplied(255, 255, 255, 255),
                    },
                    expansion: 1.0,
                },
                open: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(27, 27, 27, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(27, 27, 27, 255),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(60, 60, 60, 255),
                    },
                    corner_radius: CornerRadius {
                        nw: 2,
                        ne: 2,
                        sw: 2,
                        se: 2,
                    },
                    fg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(210, 210, 210, 255),
                    },
                    expansion: 0.0,
                },
            },

            selection: Selection {
                bg_fill: Color::rgb(0, 92, 128).build(),
                stroke: Stroke {
                    width: 1.0,
                    color: Color::rgb(192, 222, 255).build(),
                },
            },
            hyperlink_color: Color32::from_rgba_premultiplied(90, 170, 255, 255),
            faint_bg_color: Color::rgb(5, 5, 5).with_alpha(0).build(),
            extreme_bg_color: Color32::from_rgba_premultiplied(10, 10, 10, 255),
            code_bg_color: Color32::from_rgba_premultiplied(64, 64, 64, 255),
            warn_fg_color: Color32::from_rgba_premultiplied(255, 143, 0, 255),
            error_fg_color: Color32::from_rgba_premultiplied(255, 0, 0, 255),
            window_corner_radius: CornerRadius {
                nw: 6,
                ne: 6,
                sw: 6,
                se: 6,
            },
            window_shadow: Shadow {
                // extrusion: 32.0,
                color: Color32::from_rgba_premultiplied(0, 0, 0, 96),
                offset: [3, 3],
                blur: 3,
                spread: 3,
            },
            // window_fill: Color32::from_rgba_premultiplied(27, 27, 27, 255),
            window_fill: Color32::from_rgba_premultiplied(0, 0, 0, 255),

            window_stroke: Stroke {
                width: 1.0,
                color: Color32::from_rgba_premultiplied(60, 60, 60, 255),
            },
            menu_corner_radius: CornerRadius {
                nw: 6,
                ne: 6,
                sw: 6,
                se: 6,
            },
            panel_fill: Color32::from_rgba_premultiplied(27, 27, 27, 255),
            popup_shadow: Shadow {
                // extrusion: 16.0,
                color: Color32::from_rgba_premultiplied(0, 0, 0, 96),
                offset: [3, 3],
                blur: 3,
                spread: 3,
            },
            resize_corner_size: 12.0,
            // text_cursor_width: 2.0,
            // text_cursor_preview: false,
            button_frame: true,
            collapsing_header_frame: false,
            indent_has_left_vline: true,
            striped: false,
            slider_trailing_fill: false,
            window_highlight_topmost: true,

            text_cursor: Default::default(),
            handle_shape: HandleShape::Circle,
            interact_cursor: None,
            image_loading_spinners: true,
            numeric_color_space: NumericColorSpace::GammaByte,
            ..Visuals::dark()
        },
        animation_time: 0.083_333_336,
        explanation_tooltips: false,
        ..Default::default()
    }
}
