name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust 1.78
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: clippy, rustfmt

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --profile ci --workspace

      - name: Clippy
        run: cargo clippy --all --no-deps --all-features --tests


  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust 1.78
        uses: dtolnay/rust-toolchain@1.78.0

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: test lang
        run: cargo nextest run --workspace --bins --lib --tests --examples --no-fail-fast
